### PR TITLE
Remove "Actively Recruiting" from project status

### PR DESCRIPTION
**Pull request by caseypugh**
- Shouldnt have been a status in the first place since it is duplicating the point of `accepting_volunteers?` boolean.
- Turned on validation of project status, but defaulting to the first status, `Just started` if nil. Perhaps I should update all status=nil to that status and remove this before validation?
- Migration to update any projects that happened to set that status

### CODE REVIEW

**Comment by jamiew** [comment]
Code looks good and running a manual check in a sec

Only possible issue is migration sets "Actively recruiting" project statuses to "Idea." Do we have any projects with the "Actively recruiting" status? Migration might be overkill if so

Overdue to refactor these statuses into symbols mapped to strings too

**Comment by jamiew** [comment]
Just pushed a fix so the migration changes them from "Actively recruiting" to "In Progress" instead of "Just started"

**Comment by sradu** [comment]
@caseypugh @jamiew can you please fix the merge conflicts?

**Comment by caseypugh** [comment]
@sradu let's not merge PRs when specs are failing!

**Comment by sradu** [comment]
Sounds good! Will pay attention next time.

**Pull request merged**
