### PR TITLE
Make text and color changes to homepage

### PR DESCRIPTION
**Pull request by shen-sat**
These are text (and styling/color) changes relating to what HWBE will be focusing on in the near- and far-term.

### CODE REVIEW

**Comment by sradu** [comment]
@shen-sat 
Only make changes in themes/ unless you want it to apply everywhere. Improve the theming system otherwise.

Meaning:
1) if it's a new feature that a lot of projects might want to use: add to the main app
2) if it's anything hbwe related do it in themes.

**Review by sradu — CHANGES_REQUESTED** [review]
See main comment.

**Comment by jamiew** [comment]
+1. That category-info hardcoded switch statement might require factoring those out into `Settings`?

**Comment by shen-sat** [comment]
> @shen-sat
> Only make changes in themes/ unless you want it to apply everywhere. Improve the theming system otherwise.
> 
> Meaning:
> 
>     1. if it's a new feature that a lot of projects might want to use: add to the main app
> 
>     2. if it's anything hbwe related do it in themes.

I'm not sure I understand: the feature is hwbe-related, so I put the changes in the hwbe seetings file - is that not correct?

**Comment by shen-sat** [comment]
> +1. That category-info hardcoded switch statement might require factoring those out into `Settings`?

Sorry @jamiew feel like my brain is not working today - what do you mean by factoring the switch statement into `Settings`? We need the switch statement to decide the bg_color for projects, no?

**Comment by jamiew** [comment]
Basically the edits to `app/views/projects/_category-info.html.erb` and `tailwind.config.js` are to the "base app" that Radu mentioned, rather than the HWBE theme. 

If possible it would be best to put those tailwind changes into the `theme/` config config, and refactor the `_category-info.html.erb` partial to look for color values from the global `Settings` instead of being hard-coded like that. It looks like that was one file that we did not really make theme-friendly yet

**Comment by shen-sat** [comment]
> Basically the edits to `app/views/projects/_category-info.html.erb` and `tailwind.config.js` are to the "base app" that Radu mentioned, rather than the HWBE theme.
> 
> If possible it would be best to put those tailwind changes into the `theme/` config config, and refactor the `_category-info.html.erb` partial to look for color values from the global `Settings` instead of being hard-coded like that. It looks like that was one file that we did not really make theme-friendly yet

I see! That makes sense - I'm clearly still figuring out how the theme works :) I'll make the changes 👍

**Comment by shen-sat** [comment]
Closing this PR as it is adressed in another PR: https://github.com/helpwithcovid/covid-volunteers/pull/290

> Basically the edits to `app/views/projects/_category-info.html.erb` and `tailwind.config.js` are to the "base app" that Radu mentioned, rather than the HWBE theme.
> 
> If possible it would be best to put those tailwind changes into the `theme/` config config, and refactor the `_category-info.html.erb` partial to look for color values from the global `Settings` instead of being hard-coded like that. It looks like that was one file that we did not really make theme-friendly yet

In the new PR I've moved the changes into the 'theme' side of the app, rather than the base app. I haven't made the requested changes to `_category-info.html.erb`, as per the comment here: https://github.com/helpwithcovid/covid-volunteers/pull/290#discussion_r473142510

**Pull request closed without merging**
