### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by ivanoblomov**
I added a [Spanish translation](https://github.com/helpwithcovid/covid-volunteers/pull/268) to the `helpwithblackequity` branch, but I think it will work for the main branch too.

As noted in the original PR, we may want a native speaker to [review it for idiomatic accuracy](https://github.com/helpwithcovid/covid-volunteers/pull/268#issue-455932976).

### CODE REVIEW

**Comment by jamiew** [comment]
Thank you! I think we might need to do some frontend magic to get this fully working – @adrianthedev are you familiar with how the app/frontend/packs/translations/en.js.erb files work? Do we need one per-language, or would we just bundle them all together?

**Comment by jamiew** [comment]
I think we might need some Rails-level configuration to make sure it loads the visitors language as well. I merged the prior PR into `helpwithblackequity` branch but didn't get a chance to fully test yet

**Comment by adrianthedev** [comment]
Hmm. IDK how those work or how to get the visitor's locale off the top of my head. I clocked out for the night but I can have a look tmr.

**Comment by jamiew** [comment]
OK I figured that part out. Going ahead and merging. Thank you @ivanoblomov!

**Comment by jamiew** [comment]
Oops, I had to add two more fixes so Rails would load this:

* 0821e3563b501eff7d4e31fd53f769e66189a2eb
* 74df17ad2d26d415a34c4b865c6421ea8824e6ed

**Comment by jamiew** [comment]
@sradu @adrianthedev if you'd like to test locale, use `?locale=es` on any page. Or adjust your browser settings so it sends es or es-* for `HTTP_ACCEPT_LANGUAGE`

**Pull request merged**
